INSERT INTO retailers (name, location, website, delivery_fee, kosher, notes) VALUES
('עיראקי מקור הבשר', 'טירה, ראשלצ, ראש העין', 'https://bneiraqi.co.il/', '40', false, 'בשר טרי'),
('בשר פרימיום', 'משלוח מרכז-צפון', 'https://www.facebook.com/%D7%91%D7%A9%D7%A8-%D7%A4%D7%A8%D7%99%D7%9E%D7%99%D7%95%D7%9D-1944734272411492', 'חינם מעל 500', false, 'בשר טרי'),
('קרל ברג', 'כל הארץ', 'https://karlberg.co.il/home', 'לא', false, 'בשר טרי'),
('דבאח גן שמואל', 'טירה,ראשלצ,גן שמואל,כרמיאל', 'https://www.duchan.co.il/', 'לא', false, 'בשר טרי'),
('קשת טעמים', 'כל הארץ', 'https://www.keshet-teamim.co.il/', '30', false, 'בשר טרי'),
('טיב טעם', 'כל הארץ', 'https://www.tivtaam.co.il/', '?', false, 'בשר טרי'),
('הצרכניה', 'אבן יהודה', 'https://www.hazarhaniya.com/', '?', false, 'בשר טרי'),
('ולדמן', 'אשדוד', 'https://valdman.shopo.co.il/', 'חינם מעל 300', false, 'בשר טרי'),
('שמשון כהן', 'ת"א', 'https://www.facebook.com/ShimshonCohen.meat/', '120 לשרון', false, 'בשר טרי'),
('קנקון', 'מודיעין,אשדוד', 'https://cancun.co.il/', '?', false, 'בשר טרי'),
('סוד הבשר', 'כפס', 'http://www.sodhabasar.co.il/', '?', false, 'בשר טרי'),
('חינאווי', NULL, 'http://www.hinnawi.com/', '30-80', false, 'בשר טרי'),
('בשר בכפר', 'אבו גוש', 'https://www.basar-bakfar.co.il/', '30', false, 'בשר טרי'),
('רמי לוי', 'כל הארץ', 'https://www.rami-levy.co.il/he/shop', NULL, true, 'בשר טרי'),
('מעדני גורמה', 'מרכז', 'online.gorme.co.il', NULL, true, 'בשר טרי'),
('איתן מעדני בשר', 'כל הארץ', 'http://www.eitan-meat.co.il/', '?', true, 'בשר טרי'),
('באפלו מיטליז', 'ב"ש', 'https://meat-buffalo.co.il/', '?', true, 'בשר טרי'),
('אטיאסדו', 'ב"ש', 'https://atiasado.co.il/', '25-65', true, 'בשר טרי'),
('הכהנים', 'נהריה', 'https://hacohenimeat.co.il/', 'חינם מעל 700', true, 'בשר טרי'),
('החלוצים', 'משלוח מרכז-צפון', 'https://www.hachalutzim.co.il/', '30', true, 'בשר טרי'),
('מיט פלייס', 'אשקלון', 'https://meat-place.co.il/', 'חינם מעל 550', true, 'בשר טרי'),
('בשר בעיר', 'חדרה', 'http://Citymeat.co.il/', NULL, true, 'בשר טרי'),
('פסקוביץ', 'משלוח אשקלון-נתניה', 'https://shop.paskovich.co.il/', NULL, true, 'בשר טרי'),
('דובלה', 'כפר יהושע', 'https://www.dovaleh.co.il/', NULL, false, 'בשר קפוא'),
('צמד קצבים', 'גני תקוה', NULL, NULL, false, 'עדכון בקרוב'),
('נתח בשרים', 'אורנית', 'https://0515900450.co.il/', NULL, false, 'עדכון בקרוב'),
('ויקטורי', 'כל הארץ', 'https://www.victoryonline.co.il/', NULL, true, 'עדכון בקרוב'),
('שירי', 'ב"ש', 'http://shiri2go.co.il/', NULL, false, 'עדכון בקרוב'),
('blue cow', 'שדרות', 'https://www.thebluecow.co.il/', NULL, false, 'עדכון בקרוב'),
('שף בשר', 'רחובות', 'http://shefbasar.co.il/', NULL, false, 'עדכון בקרוב');
